services:
  backend:
    container_name: backend
    hostname: backend
    build:
      context: .
      dockerfile: build/backend/Dockerfile
    volumes:
      - ./build/backend/entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy

  message_handler:
    container_name: message_handler
    hostname: message_handler
    build:
      context: .
      dockerfile: build/message_handler/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy

  kafka-init:
    image: apache/kafka:4.2.0
    volumes:
      - ./build/kafka/create_topic_entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    entrypoint: ["/entrypoint.sh"]
    restart: "no"

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    restart: always
    volumes:
      - db_local:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka1:
    image: apache/kafka:4.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "19092:9092"
      - "19093:9093"
    volumes:
      - ./build/kafka/config/kafka-raft-1.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka1-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:19092"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka2:
    image: apache/kafka:4.2.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "29092:9092"
      - "29093:9093"
    volumes:
      - ./build/kafka/config/kafka-raft-2.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka2-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:29092"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka3:
    image: apache/kafka:4.2.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "39092:9092"
      - "39093:9093"
    volumes:
      - ./build/kafka/config/kafka-raft-3.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka3-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8181:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    restart: unless-stopped

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  db_local:
