services:
  postgres:
    image: postgres:18-alpine
    restart: always
    volumes:
      - db_local:/usr/lib/postgresql/18/bin
    ports:
      - "5432:5432"
    env_file:
      - .env

  kafka1:
    image: apache/kafka:4.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "19092:9091"
    volumes:
      - ./build/kafka/config/kafka-raft-1.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka1-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka2:
    image: apache/kafka:4.2.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9094:9092"
      - "19093:9091"
    volumes:
      - ./build/kafka/config/kafka-raft-2.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka2-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka3:
    image: apache/kafka:4.2.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9095:9092"
      - "19094:9091"
    volumes:
      - ./build/kafka/config/kafka-raft-3.properties:/var/lib/kafka/kraft.properties
      - ./build/kafka/entrypoint.sh:/entrypoint.sh
      - kafka3-data:/var/lib/kafka/data
    entrypoint:
      - /entrypoint.sh
    networks:
      - kafka-net
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9092,kafka3:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    networks:
      - kafka-net
    restart: unless-stopped

volumes:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  db_local:

networks:
  kafka-net:
    driver: bridge